//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorfulBox.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorfulBox.Localization.Labels", typeof(Labels).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A simple and useful palette application that allows you to select colors from a HSV color wheel and save them as XAML. 的本地化字符串。
        /// </summary>
        public static string AboutAppMessage {
            get {
                return ResourceManager.GetString("AboutAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analogous 的本地化字符串。
        /// </summary>
        public static string Analogous {
            get {
                return ResourceManager.GetString("Analogous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Palette 的本地化字符串。
        /// </summary>
        public static string ColorPalette {
            get {
                return ResourceManager.GetString("ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complementary 的本地化字符串。
        /// </summary>
        public static string Complementary {
            get {
                return ResourceManager.GetString("Complementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copoied 的本地化字符串。
        /// </summary>
        public static string Copoied {
            get {
                return ResourceManager.GetString("Copoied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UseSystemSetting 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Like 的本地化字符串。
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monochromatic 的本地化字符串。
        /// </summary>
        public static string Monochromatic {
            get {
                return ResourceManager.GetString("Monochromatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization 的本地化字符串。
        /// </summary>
        public static string Personalization {
            get {
                return ResourceManager.GetString("Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must restart your app before the new setting will take effect. 的本地化字符串。
        /// </summary>
        public static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule 的本地化字符串。
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shades 的本地化字符串。
        /// </summary>
        public static string Shades {
            get {
                return ResourceManager.GetString("Shades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme Mode 的本地化字符串。
        /// </summary>
        public static string ThemeMode {
            get {
                return ResourceManager.GetString("ThemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triad 的本地化字符串。
        /// </summary>
        public static string Triad {
            get {
                return ResourceManager.GetString("Triad", resourceCulture);
            }
        }
    }
}
